# Start from the Python 3.13.7 base image
FROM python:3.13.7

# Install system dependencies (including libGL and build essentials)
RUN apt-get update && apt-get install -y \
    libgl1 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*  # Clean up the apt cache to reduce image size

# Create a new non-root user and switch to that user
RUN useradd -m -u 1000 user
USER user

# Set the PATH to include local user binaries
ENV PATH="/home/user/.local/bin:$PATH"

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file with proper ownership
COPY --chown=user ./requirements.txt requirements.txt

# Install Python dependencies from the requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Application codes
COPY --chown=user ./app /app/app
COPY --chown=user ./data /app/data

COPY --chown=user .env /app/.env

# Command to run the application using Streamlit
CMD ["streamlit", "run", "app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]